/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// This file is regenerated by the TanStack Start Vite plugin.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TestsTestCaseIdRouteImport } from "./routes/tests.$testCaseId";
import { Route as RunsRunIdRouteImport } from "./routes/runs.$runId";
import { Route as ModelsModelIdRouteImport } from "./routes/models.$modelId";
import { Route as CompareRouteImport } from "./routes/compare";
import { Route as IndexRouteImport } from "./routes/index";

const TestsTestCaseIdRoute = TestsTestCaseIdRouteImport.update({
  id: "/tests/$testCaseId",
  path: "/tests/$testCaseId",
  getParentRoute: () => rootRouteImport,
} as any);

const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: "/runs/$runId",
  path: "/runs/$runId",
  getParentRoute: () => rootRouteImport,
} as any);

const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: "/models/$modelId",
  path: "/models/$modelId",
  getParentRoute: () => rootRouteImport,
} as any);

const CompareRoute = CompareRouteImport.update({
  id: "/compare",
  path: "/compare",
  getParentRoute: () => rootRouteImport,
} as any);

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/compare": typeof CompareRoute;
  "/models/$modelId": typeof ModelsModelIdRoute;
  "/runs/$runId": typeof RunsRunIdRoute;
  "/tests/$testCaseId": typeof TestsTestCaseIdRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/compare": typeof CompareRoute;
  "/models/$modelId": typeof ModelsModelIdRoute;
  "/runs/$runId": typeof RunsRunIdRoute;
  "/tests/$testCaseId": typeof TestsTestCaseIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/compare": typeof CompareRoute;
  "/models/$modelId": typeof ModelsModelIdRoute;
  "/runs/$runId": typeof RunsRunIdRoute;
  "/tests/$testCaseId": typeof TestsTestCaseIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/compare"
    | "/models/$modelId"
    | "/runs/$runId"
    | "/tests/$testCaseId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/compare"
    | "/models/$modelId"
    | "/runs/$runId"
    | "/tests/$testCaseId";
  id:
    | "__root__"
    | "/"
    | "/compare"
    | "/models/$modelId"
    | "/runs/$runId"
    | "/tests/$testCaseId";
  fileRoutesById: FileRoutesById;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/compare": {
      id: "/compare";
      path: "/compare";
      fullPath: "/compare";
      preLoaderRoute: typeof CompareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/models/$modelId": {
      id: "/models/$modelId";
      path: "/models/$modelId";
      fullPath: "/models/$modelId";
      preLoaderRoute: typeof ModelsModelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/runs/$runId": {
      id: "/runs/$runId";
      path: "/runs/$runId";
      fullPath: "/runs/$runId";
      preLoaderRoute: typeof RunsRunIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tests/$testCaseId": {
      id: "/tests/$testCaseId";
      path: "/tests/$testCaseId";
      fullPath: "/tests/$testCaseId";
      preLoaderRoute: typeof TestsTestCaseIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren = {
  IndexRoute,
  CompareRoute,
  ModelsModelIdRoute,
  RunsRunIdRoute,
  TestsTestCaseIdRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router";
import type { createStart } from "@tanstack/react-start";

declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
